title: BrightShard
email: brightshard@brightshard.dev
description: >-
  My open-source projects and blog.
baseurl: ""
url: "https://brightshard.dev"

# Catch all errors at build-time
liquid:
  error_mode: strict
  strict_filters: true
strict_front_matter: true

# Custom page collections
collections:
  # Collection for all of my projects
  projects:
    output: true
    permalink: /:collection/:name

# Generate an Atom feed for the blog
plugins:
  - jekyll-feed

# Feed config
feed:
  disable_in_development: true
  categories:
    - updates
    - tutorials
